mkdir ../../data/imagesLBHLBH
mkdir ../../data/imagesLBHLBH/batch1
mkdir ../../data/imagesLBHLBH/batch1/Dejan
mkdir ../../data/imagesLBHLBH/batch1/Diego
mkdir ../../data/imagesLBHLBH/batch1/Martin
mkdir ../../data/imagesLBHLBH/batch1/Oliver
mkdir ../../data/imagesLBHLBH/batch1/Rebekka
mkdir ../../data/imagesLBHLBH/batch1/Ruedi
mkdir ../../data/imagesLBHLBH/batch2
mkdir ../../data/imagesLBHLBH/batch1/Dejan
mkdir ../../data/imagesLBHLBH/batch2/Dejan
mkdir ../../data/imagesLBHLBH/batch2/Diego
mkdir ../../data/imagesLBHLBH/batch2/Martin
mkdir ../../data/imagesLBHLBH/batch2/Oliver
mkdir ../../data/imagesLBHLBH/batch2/Rebekka
mkdir ../../data/imagesLBHLBH/batch2/Ruedi
