mkdir ../../data/images
mkdir ../../data/images/batch1
mkdir ../../data/images/batch1/Dejan
mkdir ../../data/images/batch1/Diego
mkdir ../../data/images/batch1/Martin
mkdir ../../data/images/batch1/Oliver
mkdir ../../data/images/batch1/Rebekka
mkdir ../../data/images/batch1/Ruedi
mkdir ../../data/images/batch2
mkdir ../../data/images/batch1/Dejan
mkdir ../../data/images/batch2/Dejan
mkdir ../../data/images/batch2/Diego
mkdir ../../data/images/batch2/Martin
mkdir ../../data/images/batch2/Oliver
mkdir ../../data/images/batch2/Rebekka
mkdir ../../data/images/batch2/Ruedi
